export type WcagLevel = "A" | "AA" | "AAA";

export interface WcagCriterion {
  id: string; // e.g. "2.1.1"
  name: string;
  level: WcagLevel;
  version: "2.0" | "2.1" | "2.2";
  summary: string;
  understandingUrl: string;
}

// Practical subset of WCAG 2.2 success criteria most relevant to interactive
// UI component patterns (not the full 50+ SC list — see w3.org for that).
export const WCAG_CRITERIA: WcagCriterion[] = [
  {
    id: "1.1.1",
    name: "Non-text Content",
    level: "A",
    version: "2.0",
    summary: "Icons, images, and controls without visible text have a text alternative.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html",
  },
  {
    id: "1.2.1",
    name: "Audio-only and Video-only (Prerecorded)",
    level: "A",
    version: "2.0",
    summary: "Prerecorded audio-only has a transcript; prerecorded video-only has a description or transcript.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/audio-only-and-video-only-prerecorded.html",
  },
  {
    id: "1.2.2",
    name: "Captions (Prerecorded)",
    level: "A",
    version: "2.0",
    summary: "Synchronized captions are provided for prerecorded video that has an audio track.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/captions-prerecorded.html",
  },
  {
    id: "1.2.3",
    name: "Audio Description or Media Alternative (Prerecorded)",
    level: "A",
    version: "2.0",
    summary: "Prerecorded video provides audio description of the visuals, or a full text alternative for the media.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/audio-description-or-media-alternative-prerecorded.html",
  },
  {
    id: "1.2.5",
    name: "Audio Description (Prerecorded)",
    level: "AA",
    version: "2.0",
    summary: "Prerecorded video provides audio description of important visual information not conveyed by the audio.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/audio-description-prerecorded.html",
  },
  {
    id: "1.3.1",
    name: "Info and Relationships",
    level: "A",
    version: "2.0",
    summary: "Structure and relationships conveyed visually are also programmatically determinable.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html",
  },
  {
    id: "1.3.5",
    name: "Identify Input Purpose",
    level: "AA",
    version: "2.1",
    summary: "Form fields collecting common user info use correct autocomplete attributes.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/identify-input-purpose.html",
  },
  {
    id: "1.4.1",
    name: "Use of Color",
    level: "A",
    version: "2.0",
    summary: "Color is not the only visual means of conveying information or state.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html",
  },
  {
    id: "1.4.2",
    name: "Audio Control",
    level: "A",
    version: "2.0",
    summary: "Audio that plays automatically for more than 3 seconds can be paused, stopped, or muted independently.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/audio-control.html",
  },
  {
    id: "1.4.3",
    name: "Contrast (Minimum)",
    level: "AA",
    version: "2.0",
    summary: "Text has a contrast ratio of at least 4.5:1 (3:1 for large text).",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html",
  },
  {
    id: "1.4.4",
    name: "Resize Text",
    level: "AA",
    version: "2.0",
    summary: "Text can be resized up to 200% without loss of content or functionality.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html",
  },
  {
    id: "1.4.10",
    name: "Reflow",
    level: "AA",
    version: "2.1",
    summary: "Content reflows to a single column at 320 CSS px wide without two-dimensional scrolling.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/reflow.html",
  },
  {
    id: "1.4.11",
    name: "Non-text Contrast",
    level: "AA",
    version: "2.1",
    summary: "UI component boundaries/states and graphical objects have 3:1 contrast against adjacent colors.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html",
  },
  {
    id: "1.4.12",
    name: "Text Spacing",
    level: "AA",
    version: "2.1",
    summary: "No loss of content when users override line, paragraph, letter, and word spacing.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/text-spacing.html",
  },
  {
    id: "1.4.13",
    name: "Content on Hover or Focus",
    level: "AA",
    version: "2.1",
    summary: "Content revealed on hover/focus (e.g. tooltips) is dismissible, hoverable, and persistent.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/content-on-hover-or-focus.html",
  },
  {
    id: "2.1.1",
    name: "Keyboard",
    level: "A",
    version: "2.0",
    summary: "All functionality is operable through a keyboard interface with no specific timing.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html",
  },
  {
    id: "2.1.2",
    name: "No Keyboard Trap",
    level: "A",
    version: "2.0",
    summary: "Keyboard focus can always be moved away from a component using standard navigation.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/no-keyboard-trap.html",
  },
  {
    id: "2.2.2",
    name: "Pause, Stop, Hide",
    level: "A",
    version: "2.0",
    summary: "Moving, blinking, or auto-updating content lasting more than 5 seconds can be paused, stopped, or hidden.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/pause-stop-hide.html",
  },
  {
    id: "2.4.1",
    name: "Bypass Blocks",
    level: "A",
    version: "2.0",
    summary: "A mechanism (such as a skip link or landmarks) is available to bypass blocks of content repeated on multiple pages.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks.html",
  },
  {
    id: "2.4.2",
    name: "Page Titled",
    level: "A",
    version: "2.0",
    summary: "Each page has a title that describes its topic or purpose.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/page-titled.html",
  },
  {
    id: "2.4.3",
    name: "Focus Order",
    level: "A",
    version: "2.0",
    summary: "Focusable components receive focus in an order that preserves meaning and operability.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html",
  },
  {
    id: "2.4.4",
    name: "Link Purpose (In Context)",
    level: "A",
    version: "2.0",
    summary: "The purpose of each link is clear from its text, or from its text plus programmatic context.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context.html",
  },
  {
    id: "2.4.6",
    name: "Headings and Labels",
    level: "AA",
    version: "2.0",
    summary: "Headings and labels describe topic or purpose.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels.html",
  },
  {
    id: "2.4.7",
    name: "Focus Visible",
    level: "AA",
    version: "2.0",
    summary: "Any keyboard-operable UI has a visible focus indicator.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html",
  },
  {
    id: "2.4.11",
    name: "Focus Not Obscured (Minimum)",
    level: "AA",
    version: "2.2",
    summary: "The focused element is not entirely hidden by author-created content (e.g. sticky headers).",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html",
  },
  {
    id: "2.4.13",
    name: "Focus Appearance",
    level: "AAA",
    version: "2.2",
    summary: "The focus indicator is large enough and has sufficient contrast against adjacent colors.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html",
  },
  {
    id: "2.5.1",
    name: "Pointer Gestures",
    level: "A",
    version: "2.1",
    summary: "Path-based or multipoint gestures have a single-pointer alternative.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/pointer-gestures.html",
  },
  {
    id: "2.5.2",
    name: "Pointer Cancellation",
    level: "A",
    version: "2.1",
    summary: "Functions triggered by a single pointer can be aborted or undone before completion.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/pointer-cancellation.html",
  },
  {
    id: "2.5.3",
    name: "Label in Name",
    level: "A",
    version: "2.1",
    summary: "The accessible name contains the visible text label.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/label-in-name.html",
  },
  {
    id: "2.5.7",
    name: "Dragging Movements",
    level: "AA",
    version: "2.2",
    summary: "Functionality using a dragging movement has a single-pointer alternative (e.g. slider with buttons).",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html",
  },
  {
    id: "2.5.8",
    name: "Target Size (Minimum)",
    level: "AA",
    version: "2.2",
    summary: "Pointer targets are at least 24x24 CSS pixels, unless spaced, inline, or essential.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html",
  },
  {
    id: "3.1.1",
    name: "Language of Page",
    level: "A",
    version: "2.0",
    summary: "The default human language of the page is programmatically set (e.g. <html lang>).",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/language-of-page.html",
  },
  {
    id: "3.2.1",
    name: "On Focus",
    level: "A",
    version: "2.0",
    summary: "Receiving focus does not trigger an unexpected change of context.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/on-focus.html",
  },
  {
    id: "3.2.2",
    name: "On Input",
    level: "A",
    version: "2.0",
    summary: "Changing a setting does not automatically trigger an unexpected change of context.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/on-input.html",
  },
  {
    id: "3.3.1",
    name: "Error Identification",
    level: "A",
    version: "2.0",
    summary: "Input errors are identified and described to the user in text.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/error-identification.html",
  },
  {
    id: "3.3.2",
    name: "Labels or Instructions",
    level: "A",
    version: "2.0",
    summary: "Labels or instructions are provided when content requires user input.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html",
  },
  {
    id: "3.3.3",
    name: "Error Suggestion",
    level: "AA",
    version: "2.0",
    summary: "If an input error is detected and suggestions are known, they are provided to the user.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/error-suggestion.html",
  },
  {
    id: "3.3.7",
    name: "Redundant Entry",
    level: "A",
    version: "2.2",
    summary: "Information previously entered is auto-populated or available for the user to select.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html",
  },
  {
    id: "4.1.2",
    name: "Name, Role, Value",
    level: "A",
    version: "2.0",
    summary: "For all UI components, name, role, and value are programmatically determinable; states and changes are announced.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html",
  },
  {
    id: "4.1.3",
    name: "Status Messages",
    level: "AA",
    version: "2.1",
    summary: "Status messages can be programmatically determined via role or properties (e.g. aria-live) without receiving focus.",
    understandingUrl: "https://www.w3.org/WAI/WCAG22/Understanding/status-messages.html",
  },
];

export function getCriterion(id: string): WcagCriterion | undefined {
  return WCAG_CRITERIA.find((c) => c.id === id);
}
